catalog:
  '@antfu/eslint-config': ^4.15.0
  '@antfu/ni': ^25.0.0
  '@types/node': ^24.0.3
  bumpp: ^10.2.0
  convert: ^5.12.0
  decimal.js: ^10.5.0
  eslint: ^9.29.0
  taze: ^19.1.0
  tsdown: ^0.12.8
  typescript: ^5.8.3
  vitest: ^3.2.4
